### ISSUE TITLE
Add pip support

### ISSUE THREAD

**Issue by maikel** [maikel/taxicam#1]
See this link [Packaging and Distributing Projects](http://python-packaging-user-guide.readthedocs.org/en/latest/distributing/) to learn how to setup an installation process for this project.

**Comment by nicknad** [comment]
* install pip and virtualenv 
 * create virtual enviroment with "virtualenv 'path-to-venv'"
 * install numpy and opencv globally on your system (see http://ntraft.com/opencv-in-a-virtualenv/)
 * get local packages by: 'path-to-venv'/bin/pip install -e .
 * copy the cv files to your virtualenv: into 'path-to-venv'/lib/python2.7/site-packages
 * run program with 'path-to-venv'/bin/python scan_cam.py
